machine:
  pre:
    - sudo apt-get install build-essentials
  
  python:
    version: 2.7.10


dependencies:
  pre:
    - pip install --upgrade pip
    - pip install Cython --install-option="--no-cython-compile"
    - pip install numpy
    - pip install nosetests


test:
  override:
    nosetests -s tests/kmer_tests.py