machine:
  python:
    version: 2.7.10

dependencies:
  pre:
    - pip install --upgrade pip
    - pip install Cython --install-option="--no-cython-compile"
    - pip install numpy
    - python hashers/setup.py build_ext --inplace

test:
  override:
    - python spire.py -q ATCGGATCGAATCG -r ATCGATCGATCGATCG -k 3 -m deep -n 500
